name: niblin
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Core packages
  flutter_riverpod: 2.6.1
  riverpod_annotation: 2.6.1
  go_router: 16.1.0
  shared_preferences: 2.5.3

  # Notifications
  flutter_local_notifications: 19.4.0
  timezone: 0.10.1

  # Firebase
  firebase_core: 4.0.0
  firebase_auth: 6.0.0
  cloud_firestore: 6.0.0
  firebase_crashlytics: 5.0.0
  firebase_storage: 13.0.0

  # Authentication
  google_sign_in: 7.1.1
  sign_in_with_apple: 7.0.1

  # UI packages
  cupertino_icons: 1.0.8
  google_fonts: 6.3.0
  intl: 0.20.2
  flutter_screenutil: 5.9.3
  cached_network_image: 3.4.1
  flutter_cache_manager: ^3.4.1
  phosphor_flutter: 2.1.0

  # Animations
  lottie: 3.3.1

  # HTTP
  http: 1.5.0
  path_provider: ^2.1.4

  # Environment
  envied: 1.1.1

  # App Tracking
  app_tracking_transparency: 2.0.6+1
  facebook_app_events: 0.20.1
  firebase_analytics: 12.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 5.0.0
  envied_generator: 1.1.1
  build_runner: 2.4.15
  riverpod_generator: 2.6.4
  fake_cloud_firestore: ^4.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/onboarding/
    - assets/animations/onboarding/
