// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFSwdw8OhrGACoLyR8NNRtjLIpKx0-Usc',
    appId: '1:852554518025:web:80438ae435a395e22d32d8',
    messagingSenderId: '852554518025',
    projectId: 'niblin-app',
    authDomain: 'niblin-app.firebaseapp.com',
    storageBucket: 'niblin-app.firebasestorage.app',
    measurementId: 'G-PVRK1BBRV1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCijJpRyRw240DCHTOiaQ-rXt1dRKio_RI',
    appId: '1:852554518025:android:33d94956252336ea2d32d8',
    messagingSenderId: '852554518025',
    projectId: 'niblin-app',
    storageBucket: 'niblin-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4I8OIqLwRLIg59nCNZV73qUyFR8RXsqI',
    appId: '1:852554518025:ios:11a10f2e07c7a4182d32d8',
    messagingSenderId: '852554518025',
    projectId: 'niblin-app',
    storageBucket: 'niblin-app.firebasestorage.app',
    iosBundleId: 'com.hysatech.niblin',
  );
}
